### ISSUE TITLE
I need your help for hackintosh mac

### ISSUE THREAD

**Issue by lanhebe** [RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore#14]
I cannot find the appropriate smbios. Can I get a valid serial number for amd ryzen 7 3800x 8-core msi x570 a pro?

**Comment by RobyRew** [comment]
that CPU needs a different Kernel patch property

here's de guide and what you need to do in order to hace your CPU running correctly:
https://github.com/AMD-OSX/AMD_Vanilla#read-me-first

for SMBIOS you just need to generate your own, follow this guide after the first one:
https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

Read carefully and do what you are indicated to do
