### ISSUE TITLE
Computer restarts on shutdown.

### ISSUE THREAD

**Issue by SanoranX** [RobyRew/MSI_X570_A-Pro_Hackintosh_OpenCore#5]
There is a problem when restarting the computer through the Apple menu it's turning on again after shutdown. 
Same motherboard but a different graphics card (5700 XT from Sapphire).

**Comment by RobyRew** [comment]
Thanks for the feedback, I hope to have a moment available to publish the settings I have in the BIOS and I will finish doing the config.plist guide.

Most likely, it is some small detail of the EFI, because according to me the Shaphire are the most compatible in hackintosh.

If I find something I will notify you immediately, thank you @SanoranX

**Comment by SanoranX** [comment]
There is another problem too. When I upload the newest EFI from your repository, it gives me a bunch of errors on startup. Something like <key> not found. As far as I know this problem appears when opencore was not updated propperly. If I will have time I will try to fix it and make a PR.

**Comment by RobyRew** [comment]
> There is another problem too. When I upload the newest EFI from your repository, it gives me a bunch of errors on startup. Something like not found. As far as I know this problem appears when opencore was not updated propperly. If I will have time I will try to fix it and make a PR.

thanks
